### ISSUE TITLE
Kicad design files

### ISSUE THREAD

**Issue by eprive** [SuperFabius/Z80-MBC2#4]
Where do I find the source iLoad file : S200718.asm ?

**Comment by Ho-Ro** [comment]
> Where do I find the source iLoad file : S200718.asm ?

**This may be helpful to someone**

I discovered this older (misleadingly named) question when I was also searching for the `iLoad` source code, and since the search was unsuccessful, I quickly [disassembled](https://github.com/Ho-Ro/Z80DisAssembler) the hex values, renamed the labels and added comments based on the source of the older `iLoad` version [S260117.asm](https://cdn.hackaday.io/files/19000812896000/S260117.asm).
The result [iLoad.asm](https://github.com/Ho-Ro/Z80-MBC2/blob/main/Z80-MBC2-SIO/S220718-D160125_IOS-Z80-MBC2-SIO/iLoad.asm) is available at my fork of [Z80-MBC2](https://github.com/Ho-Ro/Z80-MBC2), where I did some hacks for the Z80-MBC2.

Martin

**Comment by Ho-Ro** [comment]
The file `S200718 iLoad.asm` is available [there](https://github.com/SvenMb/z80-mbc2-emu/blob/ios_ram/iLoad/S200718%20iLoad.asm).
